version: "3"

services:
  node:
    build:
      context: node
      dockerfile: Dockerfile-node
    volumes:
      - xtest-front:/www/xtest-web/dist
    command: cnpm run build

volumes:
  xtest-front:
